language: rust

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    # Bare metal
    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
    - env: TARGET=thumbv7em-none-eabihf
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - staging
    - trying

notifications:
  email:
    on_success: never
